FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY FluxoDeCaixa.Api.Report/*.csproj FluxoDeCaixa.Api.Report/
COPY FluxoDeCaixa.Api.Report.Domain/*.csproj FluxoDeCaixa.Api.Report.Domain/
COPY FluxoDeCaixa.Api.Report.Infra/*.csproj FluxoDeCaixa.Api.Report.Infra/
RUN dotnet restore ./FluxoDeCaixa.Api.Report/FluxoDeCaixa.Api.Report.csproj
COPY ./ ./
RUN dotnet publish "./FluxoDeCaixa.Api.Report/FluxoDeCaixa.Api.Report.csproj" -c Release -o /app/

FROM --platform=linux/amd64 mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated10.0
WORKDIR /home/site/wwwroot
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
COPY --from=build /app .
