FROM --platform=linux/amd64 alpine:3.20
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.7.8/bin/rabbitmqadmin
RUN chmod 777 rabbitmqadmin
COPY ./config-rabbit.sh .
ENTRYPOINT [ "/bin/sh", "config-rabbit.sh" ]