FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY FluxoDeCaixa.Api/*.csproj FluxoDeCaixa.Api/
COPY FluxoDeCaixa.Application/*.csproj FluxoDeCaixa.Application/
COPY FluxoDeCaixa.Domain/*.csproj FluxoDeCaixa.Domain/
COPY FluxoDeCaixa.Infra/*.csproj FluxoDeCaixa.Infra/
RUN dotnet restore ./FluxoDeCaixa.Api/FluxoDeCaixa.Api.csproj
COPY ./ ./
RUN dotnet publish ./FluxoDeCaixa.Api/FluxoDeCaixa.Api.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:7.0
EXPOSE 80
EXPOSE 443
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "FluxoDeCaixa.Api.dll"]